# Generated by Django 4.2.6 on 2024-11-21 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_position_alter_team_name_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='kills_marked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='kills_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_goals', models.PositiveIntegerField(default=0)),
                ('team2_goals', models.PositiveIntegerField(default=0)),
                ('team1_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team1', to='tournament.team')),
                ('team2_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team2', to='tournament.team')),
            ],
        ),
    ]
