# Generated by Django 4.2.6 on 2024-11-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_team_kills_marked_team_kills_received_team_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team1_id',
            new_name='team1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team2_id',
            new_name='team2',
        ),
    ]
